import type { Metadata } from 'next';

import { urbanist } from '@/models/googlefonts.model';

import '@/styles/global.css';
import { Navbar } from '@/components';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='es-PE'>
      <body className={urbanist.className}>
        <Navbar />
        {children}
      </body>
    </html>
  );
}
